### PR TITLE
Nj update local storage

### LINKED ISSUE #33: Update LocalStorage to
Currently, localStorage is storing our token as a string. But to give the user the ability to track the lists they've joined previously, we want to have this token stored in an Array so we can access the other tokens 

AC: 
- next to the join list input, a dropdown should be visible with all previously input tokens for the user to select (with submit)
- stop auto re-routing to list view once a token is added to local storage

### PR DESCRIPTION
**Pull request by artsycoder533**
## Description

This issue changes how local storage is saved.  Instead of a single token item, an array of all the tokens a user has entered are saved in local storage.  This issue also removes auto-rerouting to the list view once a token is created/input.  I also refactored some of the code, got rid of a few redundant state variables, and used more descriptive naming.

## Related Issue

closes #33 

## Acceptance Criteria

- next to the join list input, a dropdown should be visible with all previously input tokens for the user to select (with submit)
- stop auto re-routing to list view once a token is added to local storage
- the list of tokens should not contain duplicates or any tokens that do no have an existing list
- local storage should contain the active token

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|  ✓ | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Testing Steps / QA Criteria

1. In your terminal, run ```npm checkout nj-update-local-storage```
2. run ```npm start```
3. clear your local storage and refresh the app, ```keep the local storage tap open```
4. ```token``` in local storage should be blank
5. press  ```create a new list```
6. ```token``` should be set to the same value thats displayed in the ```share token``` input field
7. ```tokenList``` should be set to an array that contains the same string as the token
8. press ```create a new list``` again
9.  ```token``` should should now be equal to the new share token
10. ```tokenList``` should now contain 2 token, the previous token and the current token
11.  in local storage, click on ```tokenList``` to show the expanded array at the bottom
12. enter your name in the share token field
13. press ```Join an existing list```
14. You should see an error message above the input field that says "This token does not match an existing shopping list. Please check your input and try again."
15. In local storage, the ```token``` value should be equal to your name
16. The tokenList should ```**NOT**``` contain your name!
17. delete your name from the share token input field 
18. the token value in local storage should now be ```blank```
19. hover over the input field and you should see a caret down arrow on the righthand side
20. click the input field and a ```datalist``` should appear containing the values that are listed in the ```tokenList``` in local storage. **`(if you clicked this field without first deleting your name you will only see your name in the datalist.  The datalist acts as a filter, any options contained inside of the datalist that contain the same text as the input field will be shown.  This is why you have to first clear the datalist to show all of the tokens that have been added)`**
21. select a token from the ```datalist``` of your choosing by clicking on it
22. the token value in local storage should now be equal to the value you selected from the ```datalist```
23. in the url, replace ```localhost:3000``` with ```localhost:3000/list```
24. you should see a ```blank``` list
25. click the ```Add Item``` button
26. enter an item of your choosing
27. navigate back to the list view
28. your item should have been added to the list
29. in the url replace ```localhost:3000/list``` with ```localhost:3000```
30. In the ``share token``` input field paste ```wily dice shire``` 
31. In local storage the token should now be equal to ```wily dice shire```
32.  press ```Join and existing list```
33. In local storage ```wily dice shire``` ```**SHOULD**``` have been added to the ```tokenList```
34. in the url, replace ```localhost:3000``` with ```localhost:3000/list```
35. you should see an already populated list
36.  in the url replace ```localhost:3000/list``` with ```localhost:3000```
37. delete ```wily dice shire``` from the ```share token``` input field
38. click on the input field and ```wily dice shire``` should be included in the ```datalist```

### CODE REVIEW

**Review by sparsell — APPROVED** [review]
Super impressive. Really adds a lot of value to the app! 

Instructions were great and all results observed. 

Have only 2 comments:
1. I think the first instruction in the testing criteria should have had `git` instead of `npm` for checking out the branch. :)
2. When I have nothing in the input field, then select an existing list to join from the dropdown, and then press "Join an Existing List", I still get the error message. I know there is another issue set up to deal with navigation so this could be addressed there. 
Screen Shot 2022-05-20 at 2 14 21 PM

**Review by daniel-sj-hong — APPROVED** [review]
Awesome, thorough step of instructions. Really detailed and very easy to follow. Worked well and as intended!

**Comment by lindseyindev** [comment]
I deleted my local storage and entered this token from firebase and I think I clicked join list twice and I get this message that the token doesn't match a list 

wovepacketmaser
[here's the token in firebase ](https://console.firebase.google.com/u/2/project/tcl-40-smart-shopping-list/firestore/data/~2Fwove%20packet%20maser~2F3BDyDTsCU39nyXTW1tsY)

Is this the expected behavior? Is the list not valid or is this a bug? I'm not sure what's happening here. 

I was investigating the join list button earlier and I like the direction you're going in with this refactor! I think it will work better, especially when the input is already filled in and a user clicks the join list button

**Review by k-schrattenholzer — APPROVED** [review]
Again with the incredible testing steps! I was able to create multiple new lists, add items to them, and switch between joined lists using the drop down menu that now shows the users their joined lists.

**Pull request merged**
