### PR TITLE
dh-readme

### LINKED ISSUE #43: Update Readme
Examples of readmes 
https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

https://dev.to/github/how-to-create-the-perfect-readme-for-your-open-source-project-1k69

Basically pick categories you think would be applicable to this project and add them! What you would want someone you send this repo to see!

### PR DESCRIPTION
**Pull request by daniel-sj-hong**
## Description

Updated the README.md file to explain the overall scope of this project and what it does. Included the technologies used and everyone who contributed to the project.

## Related Issue

closes #43 

## Acceptance Criteria

- Update README.md file so that it properly reflects our work. 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|  ✓  | :scroll: Docs              |

## Testing Steps / QA Criteria

Read over the README.md file and let me know if you want me to include something that I might've missed, a typo, or anything else that you think is necessary to add to the README.md file.

### CODE REVIEW

**Review by artsycoder533 — COMMENTED** [review]
Good job Daniel! I like the image links you added to the bottom, that was a nice touch!  One thing you might want to add to "How does it work" is an explanation of the tokens and how they are attached to a list in firebase and that a user can essentially "sign into" another users list as long as they have their token. Another thing to maybe add is go a little more in depth about how the interval works (each time a user selects the checkbox the interval decreases, etc) and the list items are sorted by intervals and these intervals are indicated by a badge beside the list name.

**Review by artsycoder533 — APPROVED** [review]
Good job Daniel! I like the image links you added to the bottom, that was a nice touch!  One thing you might want to add to "How does it work" is an explanation of the tokens and how they are attached to a list in firebase and that a user can essentially "sign into" another users list as long as they have their token. Another thing to maybe add is go a little more in depth about how the interval works (each time a user selects the checkbox the interval decreases, etc) and the list items are sorted by intervals and these intervals are indicated by a badge beside the list name.

**Review by sparsell — APPROVED** [review]
Great job, Daniel. I would echo Natasha's comments about adding a little more detail about the token and token lists and how they are used in the app and Firebase, how you can share lists with others, and how the app determines when your list items are 'due' for buying again.

**Comment by daniel-sj-hong** [comment]
> Great job, Daniel. I would echo Natasha's comments about adding a little more detail about the token and token lists and how they are used in the app and Firebase, how you can share lists with others, and how the app determines when your list items are 'due' for buying again.



> Good job Daniel! I like the image links you added to the bottom, that was a nice touch! One thing you might want to add to "How does it work" is an explanation of the tokens and how they are attached to a list in firebase and that a user can essentially "sign into" another users list as long as they have their token. Another thing to maybe add is go a little more in depth about how the interval works (each time a user selects the checkbox the interval decreases, etc) and the list items are sorted by intervals and these intervals are indicated by a badge beside the list name.

So I made the suggested edits but in terms of merging this PR, I'll merge it after we're done so I can take screenshots of the final product and then add it to this README.md file. That way I can avoid creating two PRs for one file/change.

**Pull request merged**
