### PR TITLE
Created a new firestore instance

### LINKED ISSUE #45: Create new firebase firestore instance
Create on a shared email or designate someone to create and share the instance via email to the other developers

Make sure firebase hosting is setup, hosting details from the current firebase firestore instance:
https://console.firebase.google.com/u/2/project/tcl-40-smart-shopping-list/hosting/sites

### PR DESCRIPTION
**Pull request by daniel-sj-hong**
## Description

The current existing firestore instance is set to expire. Created a new firestore instance and replaced the existing firebaseConfig code in the firebase.js file with the new firebaseConfig code from the new firestore instance.

## Related Issue

closes #45 

## Acceptance Criteria

Create a new firestore instance from firebase. 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
| ✓ | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates
Nothing to test. Just updated the firebaseConfig code on the firebase.js file.

### CODE REVIEW

**Review by artsycoder533 — COMMENTED** [review]
Whats the link to this so we can see if we can read/write to it?

**Comment by daniel-sj-hong** [comment]
> Whats the link to this so we can see if we can read/write to it?

I was just getting to that. I was adding all you guys under the permissions setting for the new firestore instance.

Here's the link for the new database: https://console.firebase.google.com/project/tcl-40-smart-shopping-li-23b8c/firestore/data/~2F

**Review by artsycoder533 — APPROVED** [review]
After changing the rules in firebase I was able to read/write to the new database. Theres a list I played with called `wily dice shire` in the new db that shows each color at least for demo purposes. Since theres a new instance we'll lose all our lists, but at least all the list on this db will have consistent properties and should cause errors like the others from the old db.

**Comment by lindseyindev** [comment]
Yay for getting this working!! We dont have to merge before the demo we can continue to use the current firebase db and then just merge after demo so your app will have continued access to a db longterm

**Review by lindseyindev — APPROVED** [review]

**Pull request merged**
