### PR TITLE
Issue #1 - Connect app to Firebase

### PR DESCRIPTION
**Pull request by sparsell**
## Acceptance Criteria:

1. Making a change in the Firestore database will update the data in the App.
2. Making a change in the App will update the data in Firestore. 
(Firebase was added as a project dependency - `npm install firebase`)

## What did this code change?
 - the App and the database are now synced together
 - added temporary component "AddToFirebase.js" with a button to 
   1. send data to the database and 
   2. retrieve all the data and display it on the screen.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  x | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|   x | :link: Update dependencies |
|    | :scroll: Docs              |

### In your text editor/the app:
1. Run `npm install` (to build new Firebase dependency)
2. Run `npm start`
3. Press "Add" button 
4. User should see the words "Test" displayed above the button. 
5. Each time you press the button, another "Test" will appear. 

### In Firestore database: 
1. Load the tcl-40-shopping-list at console.firebase.com: 
[https://console.firebase.google.com/project/tcl-40-smart-shopping-list/firestore/data/~2Flist](https://console.firebase.google.com/project/tcl-40-smart-shopping-list/firestore/data/~2Flist)
2. View the collection ("list")
3. Click on the 'list' to see all individual documents (entries) in our 'list'. 
4. The far right panel will populate with details of the document. You can delete a document by using the menu in the far right corner. 
5. The item will then be removed from the list and you can see that on the screen of the app. 

Screen Shot 2022-04-05 at 1 44 10 PM

### CODE REVIEW

**Review by k-schrattenholzer — APPROVED** [review]
This looks great!

**Review by daniel-sj-hong — APPROVED** [review]
Checked the Firestore database - the data is there and seems to be working.

**Comment by lindseyindev** [comment]
I love the component separation of this code from App.js! 
Even if this is a temporary location, will make it really easy to scale and maintain separation of concerns! This can sometimes be a painful lesson as your features grow but you're team is nailing it already.

Did your team like working with firebase for this issue? How do you two feel about it?

**Comment by artsycoder533** [comment]
Lindsey,  
Working with firebase wasnt too bad once we found what we were missing in the documentation.  Firebase has always been one of those things where I feel like I never really know what i'm doing each time I work with it.

**Comment by sparsell** [comment]
@lindseyindev I had never worked with Firebase before so there was a slight learning curve but it was just a matter of reading docs and playing around with it before I started to feel more confident.

**Review by mxmason — APPROVED** [review]
Things look great to me! Like Lindsey said, I think extracting the Firebase functionality into its own component was a good move!

**Comment by artsycoder533** [comment]
closing in favor of #17

**Pull request closed without merging**
